language: python
matrix:
  include:
   - os: linux
     python: 3.5

   - os: linux
     python: nightly

   - os: osx
     language: generic
     osx_image: xcode7.3

  allow_failures:
   # Doesn't currently work with pyinstaller
   - python: nightly


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     wget -O python3.pkg https://www.python.org/ftp/python/3.5.2/python-3.5.2-macosx10.6.pkg;
     sudo installer -pkg python3.pkg -target /;
     pip3 install --upgrade pip setuptools wheel virtualenv;
     virtualenv venv -p python3;
     source venv/bin/activate;
   fi
 - python --version
 - pip install pytest pyinstaller


install:
 - "make build"

script:
 - "make test"
 - "make package"
