[tool.poetry]
name = "aw-watcher-window"
version = "0.2.0"
description = ""
authors = ["Erik Bj√§reholt <erik@bjareho.lt>"]
license = "MPL-2.0"

[tool.poetry.scripts]
aw-watcher-window = "aw_watcher_window:main"

[tool.poetry.dependencies]
python = "^3.6"
aw-client = {git = "https://github.com/ActivityWatch/aw-client.git"}
python-xlib = {version = "^0.26", platform = "linux"}
pypiwin32 = {version = "223", platform = "win32"}
wmi = {version = "^1.4.9", platform = "win32"}
pyobjc-framework-ApplicationServices = { version = "^6.2", platform="darwin"}
pyobjc-framework-CoreText = {version = "^6.2", platform="darwin"}


[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
mypy = "^0.761"
macholib = {version = "^1.13", platform = "darwin"}  # Needed for pyinstaller

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
